services:
  website:
    build: 
      context: .
      dockerfile: ./packages/website/Dockerfile
      args:
        - PUBLIC_REMARK_URL=${PUBLIC_REMARK_URL}
        - PUBLIC_SITE=${PUBLIC_SITE}
    container_name: "website"
    expose:
     - "80"
    networks:
      - billyle
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  email:
    build:
      context: .
      dockerfile: ./packages/email/Dockerfile
      args:
        - RESEND_API_KEY=${RESEND_API_KEY}
        - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
        - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
        - EMAIL_TO=${EMAIL_TO}
    container_name: "email"
    expose:
      - "${EMAIL_SERVER_PORT}"
    networks:
      - billyle
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${EMAIL_SERVER_PORT}/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  remark42:
    image: umputun/remark42:latest
    container_name: remark42
    hostname: remark42
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8081:8080"
    networks:
      - billyle 
    env_file:
      - .env
    environment:
      - REMARK_URL=${PUBLIC_REMARK_URL}
      - SITE=${PUBLIC_SITE}
      - SECRET=${REMARK_SECRET}
      - ADMIN_SHARED_ID=${ADMIN_SHARED_ID}
      - AUTH_GOOGLE_CID=${AUTH_GOOGLE_CID}
      - AUTH_GOOGLE_CSEC=${AUTH_GOOGLE_CSEC}
      - AUTH_GITHUB_CID=${AUTH_GITHUB_CID}
      - AUTH_GITHUB_CSEC=${AUTH_GITHUB_CSEC}
      - AUTH_TELEGRAM=true
      - SENTRY_ORG=billy-gr
      - SENTRY_PROJECT=javascript-astro
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - NOTIFY_ADMINS=telegram
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - NOTIFY_TELEGRAM_CHAN=${NOTIFY_TELEGRAM_CHAN}
      - ALLOWED_HOSTS=${REMARK_ALLOWED_HOSTS}
    volumes:
      - remark42:/srv/var
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  billyle:

volumes:
  remark42:
