worker_processes  1;

events {
  worker_connections  1024;
}

http {
  server {
    listen 80;
    server_name _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    client_max_body_size 10M;
    keepalive_timeout 65;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection "1; mode=block";


    location / {
      try_files $uri $uri/index.html =404;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
  }
}
